### ISSUE TITLE
Unable to send submission with Annotate/Signature widget with default image described from Collect to Central. 

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/central-backend#250] opened 2020-02-11 13:20 UTC
**Problem description:**
Error message displays when try to send a submission of from with Annotate/Signature widget with a default image defined. Screenshot attached:
![Screenshot_2020-02-11-10-06-50-821_org odk collect android](https://user-images.githubusercontent.com/33342488/74237946-f545ee00-4cd4-11ea-9fed-44ee83864d33.png)

Central does not recognize that media for that form should be added - it's probably a separate and connected issue. 

**Reproduction steps:**
 1. Add a form to Central
2. Create App User/Use existing one with form access permissions added
3. Download a form from Central to Collect
4. Fill the submission and send

**Expected results:**
Submission should be successfully sent. The error message should not display. 

**Additional informations:**
The form that I have used: 
[defaultImage.zip](https://github.com/opendatakit/central-backend/files/4185825/defaultImage.zip)

**Comment by lognaturel** [comment] 2020-02-11 15:06
Ah, I didn’t consider that this would interfere with Central. Thanks for identifying this, @kkrawczyk123. @issa-tseng more details shortly.

**Comment by florianm** [comment] 2020-02-12 02:28
This sounds similar to https://github.com/dbca-wa/ruODK/issues/41, where each submission has one attachment named "audit.csv". Downloading multiple submissions causes file name collisions.

The same assumption of "media attachments have unique file names" could create a problem with the submission export to zip, where the attachments live in one subfolder called "media". Non-unique filenames will also collide here unless @issa-tseng and @matthew-white have done some magic underneath.

**Comment by lognaturel** [comment] 2020-03-31 18:22
Thanks for chiming in, @florianm. The fact that all audit files have the same filename is indeed annoying to deal with. There are a couple of issues here and I don't think they're directly related to that one.

First, the error that @kkrawczyk123 is reporting is an interesting one and not entirely related to defaults. The issue is that it's not possible to submit two questions which use the same media file filename. The test form she has shared had two questions with default filename `doc.png`. If both of those remain unchanged, Central will complain. I think that this is ok and would recommend no action. If an actual image is set, Collect will generate a filename based on a timestamp. This problem would only occur if more than one question has the same default image URI, and at least two of those remained unchanged. I don't think it's a likely scenario and I've filed https://github.com/opendatakit/docs/issues/1184#issuecomment-606792266 so we can document how to require that an image question with a default get updated. 

Second, there's now a new place in form definitions where images to attach to the definition can be specified. For fields of image type, it's now possible to have a `jr://images/...` URI specified in the instance body:

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms">
	<h:head>
		<h:title>Default image</h:title>
		<model>
			<instance>
				<data id="defaultImage">
					<image>jr://images/doc.png</image>
					<image_widget>doc.png</image_widget>
				</data>
			</instance>
			<bind nodeset="/data/image" type="binary"/>
		</model>
	</h:head>
	<h:body>
		<upload appearance="annotate" mediatype="image/*" ref="/data/image">
			<label>Image</label>
		</upload>
	</h:body>
</h:html>
```
In that example, a file with name `doc.png` should be uploaded to Central.

This currently only applies to images (where the upload `mediatype` would be `image/*`) but it would also be fine to do the check for any node with a `binary` bind type if that's simpler.

**Comment by issa-tseng** [comment] 2020-03-31 19:14
so to clarify, the original issue this ticket was submitted for is no action, but you are requesting an unrelated change here?

**Comment by lognaturel** [comment] 2020-03-31 19:53
The action needed is to support the feature QA was verifying when the error was triggered. The issue notes that there should have been a media file upload prompt. Up to you if you want to close this and open another issue.

**Comment by issa-tseng** [comment] 2020-04-01 01:44
no, no, i was just really confused about what was happening, was all.

**Closed** 2020-04-07 01:05 UTC
